name: End To End Tests
on:
  push:
    branches:
      - master
    paths: ["pages/*", "contentful/*",'next.config.js']
jobs:
  cypress-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: build
        uses: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run start
          browser: chrome
          headless: true
